#!/bin/sh /etc/rc.common

exec &> /var/log/cake-dual-ifb.log

START=50
STOP=4

# local interfaces to combine flows from
ifaces="br-lan br-guest"

start() 
{
	# Setup dual IFBs
	ip link add name ifb-ul type ifb
	ip link add name ifb-dl type ifb
	ip link set ifb-ul up
	ip link set ifb-dl up

	for iface in $ifaces; do 

		tc qdisc add dev $iface handle ffff: ingress
		tc qdisc add dev $iface handle 1: root prio

		# capture $if (ingress) -> wan 
		# filter on fwmark 1
		tc filter add dev $iface parent ffff: protocol ip handle 1 fw flowid 1:1 action mirred egress redirect dev ifb-ul

		# capture wan -> $iface (egress) and restore DSCPs from conntracks
		# filter on fwmark 1
		tc filter add dev $iface parent 1: protocol ip handle 1 fw flowid 1:1 action ctinfo dscp 63 128 action mirred egress redirect dev ifb-dl

	done 

	tc qdisc add dev wan handle ffff: ingress
	tc qdisc add dev wan handle 1: root prio

	# capture OpenWrt -> wan (egress)
	# filter by fwmark 2 (use nftables to skip over WireGuard traffic with fwmark 3 and apply fwmark 2 to the remainder)
	tc filter add dev wan parent 1: protocol ip handle 2 fw flowid 1:1 action mirred egress redirect dev ifb-ul

	# capture wan (ingress) -> OpenWrt and restore DSCPs from conntracks
	# filter on conntrack bit 128 set
 	tc filter add dev wan parent ffff: prio 1 protocol ip matchall action ctinfo cpmark continue
	tc filter add dev wan parent ffff: prio 2 protocol ip handle 256/256 fw flowid 1:1 action ctinfo dscp 63 128 action mirred egress redirect dev ifb-dl

	# apply CAKE on the IFBs
	tc qdisc add dev ifb-ul root cake bandwidth 30Mbit diffserv4 dual-srchost nonat wash no-ack-filter noatm overhead 92
	tc qdisc add dev ifb-dl root cake bandwidth 25Mbit diffserv4 dual-dsthost nonat nowash ingress no-ack-filter noatm overhead 92
}

stop() 
{
	for iface in $ifaces; do
	
		tc qdisc del dev $iface ingress
		tc qdisc del dev $iface root

	done

	tc qdisc del dev wan ingress
	tc qdisc del dev wan root

        tc qdisc del dev ifb-ul root
        tc qdisc del dev ifb-dl root
        ip link set ifb-ul down
        ip link del ifb-ul
        ip link set ifb-dl down
        ip link del ifb-dl
} 

