#!/bin/sh /etc/rc.common

exec &> /tmp/cake-dual-ifb.log

START=50
STOP=4

start() {
	# ifb interface for handling ingress on WAN (and VPN interface if wg show reports endpoint)
	ip link add name ifb-ul type ifb
	ip link add name ifb-dl type ifb
	ip link set ifb-ul up
	ip link set ifb-dl up

	tc qdisc add dev br-lan handle ffff: ingress
	tc qdisc add dev br-guest handle ffff: ingress
	tc qdisc add dev br-lan handle 1: root prio
	tc qdisc add dev br-guest handle 1: root prio

	# capture upload (ingress) on br-lan that is not LAN-LAN and is not multicast or broadcast
	tc filter add dev br-lan parent ffff: protocol ip prio 1 u32 match ip dst 192.168.1.0/24 action pass
	tc filter add dev br-lan parent ffff: protocol ip prio 1 u32 match ip dst 224.0.0.0/4 action pass
	tc filter add dev br-lan parent ffff: protocol ip prio 1 u32 match ip dst 255.255.255.255/32 action pass
	tc filter add dev br-lan parent ffff: protocol ip prio 2 matchall action mirred egress redirect dev ifb-ul

	# capture upload (ingress) on br-guest that is not LAN-LAN and is not mutlicast or broadcast
	tc filter add dev br-guest parent ffff: protocol ip prio 1 u32 match ip dst 192.168.2.0/24 action pass
	tc filter add dev br-guest parent ffff: protocol ip prio 1 u32 match ip dst 224.0.0.0/4 action pass
	tc filter add dev br-guest parent ffff: protocol ip prio 1 u32 match ip dst 255.255.255.255/32 action pass
	tc filter add dev br-guest parent ffff: protocol ip prio 2 matchall action mirred egress redirect dev ifb-ul
       	
	# capture download (egress) on br-lan and restore DSCPs from conntracks
	tc filter add dev br-lan parent 1: protocol ip prio 1 u32 match ip src 192.168.1.0/24 action pass
	tc filter add dev br-lan parent 1: protocol ip prio 2 matchall action ctinfo dscp 63 128 action mirred egress redirect dev ifb-dl

	# capture download (egress) on br-guest and restore DSCPs from conntracks
	tc filter add dev br-guest parent 1: protocol ip prio 1 u32 match ip src 192.168.2.0/24 action pass
	tc filter add dev br-guest parent 1: protocol ip prio 2 matchall action ctinfo dscp 63 128 action mirred egress redirect dev ifb-dl

	# apply CAKE on the ifbs
	tc qdisc add dev ifb-ul root cake bandwidth 30Mbit diffserv4 triple-isolate nonat nowash no-ack-filter noatm overhead 92
	tc qdisc add dev ifb-dl root cake bandwidth 25Mbit diffserv4 triple-isolate nonat nowash ingress no-ack-filter noatm overhead 92
}

stop() {
        tc qdisc del dev br-lan ingress
        tc qdisc del dev br-guest ingress
        tc qdisc del dev br-lan root
        tc qdisc del dev br-guest root
        tc qdisc del dev ifb-ul root
        tc qdisc del dev ifb-dl root
        ip link set ifb-ul down
        ip link del ifb-ul
        ip link set ifb-dl down
        ip link del ifb-dl
} 

